# NusaTown Configuration File

# Pengaturan umum plugin
settings:
  debug-mode: false
  
# Pengaturan pesan
messages:
  prefix: "<gradient:#00A3FF:#00FFD1>NusaTown</gradient>&8 » &f"
  first-join: "<gradient:#00A3FF:#00FFD1>{player}</gradient> &bbaru saja bergabung pertama kali!"
  join: "<gradient:#00A3FF:#00FFD1>{player}</gradient> &ftelah bergabung."
  quit: "<gradient:#FF6B6B:#FF4500>{player}</gradient> &ftelah keluar."
  custom-death-message: false  # Set ke false untuk menggunakan pesan kematian vanilla
  
  # Pengaturan pesan privat
  msg-sent: "&8[&7me &8» &7{receiver}&8] &f{message}"
  msg-received: "&8[&7{sender} &8» &7me&8] &f{message}" 
  notify-sound: true      # Mainkan suara saat menerima pesan
  social-spy: true        # Fitur social spy untuk admin

# Pengaturan chat
chat:
  enabled: true                # Aktifkan format chat kustom
  use-placeholders: true       # Gunakan placeholder dari PlaceholderAPI
  discord-integration: true    # Integrasi dengan DiscordSRV
  format: "%luckperms_prefix%&f%player_name% &8» &f%message%"  # Format chat
  hover:
    enabled: true              # Tampilkan hover info saat mouse di atas nama pemain
    text:                      # Teks yang ditampilkan saat hover
      - "&7Nama: &f%player_name%"
      - "&7Rank: %luckperms_prefix%"
      - "&7Ping: &f%player_ping%ms"
      - ""
      - "&8Klik untuk mengirim pesan"
  click:
    enabled: true              # Aktifkan aksi klik pada nama pemain
    action: "SUGGEST_COMMAND"  # SUGGEST_COMMAND, RUN_COMMAND, OPEN_URL
    value: "/msg %player_name% "  # Nilai aksi (command atau URL)

# Pengaturan spawn
spawn:
  use-custom-spawn: true
  teleport-new-players: true
  instant-respawn: true      # Teleport ke spawn langsung setelah mati
  # Lokasi spawn akan ditambahkan melalui /spawn set
  
  # Proteksi di world spawn
  protection:
    enabled: true
    prevent-water-damage: true      # Teleport ke spawn jika terkena air
    prevent-void-damage: true       # Teleport ke spawn jika jatuh ke void
    void-level: -64                 # Level Y untuk mendeteksi void
    spawn-world-names:              # Nama world yang dianggap spawn world
      - "Spawn"
    teleport-message: "&cAnda telah diteleportasi kembali ke spawn."
  
# Pengaturan ekonomi
economy:
  enabled: true                # Toggle untuk mengaktifkan/menonaktifkan fitur ekonomi
  starting-balance: 1000.0     # Saldo awal untuk pemain baru
  currency:
    symbol: "$"                # Simbol mata uang
    name: "Coin"               # Nama mata uang tunggal
    name-plural: "Coins"       # Nama mata uang jamak

# Tambahkan bagian ini di bawah pengaturan ekonomi:
tokens:
  starting-amount: 0        # Jumlah token awal untuk pemain baru
  name: "Token"             # Nama token tunggal
  name-plural: "Tokens"     # Nama token jamak

# Pengaturan voting dan VoteParty
voting:
  url: "vote.nusatown.com"
  bonus-chance: 30  # Peluang mendapatkan reward bonus (%)
  rewards:
    regular:
      - "give %player% diamond 5"
      - "give %player% emerald 10"
      - "eco give %player% 3500"
      - "crate key give %player% vote_key 3"
      - "tempfly give %player% 5m"
    bonus:
      - "give %player% netherite_ingot 1"
  voteparty:
    target: 10  # Jumlah vote untuk trigger VoteParty
    rewards:
      - "give %player% diamond 3"
      - "give %player% emerald 5"
      - "crate key give %player% vote_key 1"

# Pengaturan pemain
player:
  welcome-message: "<gradient:#00A3FF:#00FFD1>Selamat datang di NusaTown!</gradient>"

# Pengaturan teleportasi
teleport:
  cooldown: 30            # Waktu cooldown antar teleport (detik)
  countdown-enabled: true  # Toggle untuk mengaktifkan/menonaktifkan countdown teleport
  delay: 3                # Waktu countdown sebelum teleport (detik)
  expire: 60              # Waktu kadaluarsa permintaan teleport (detik)
  
# Pengaturan Combat Tag
combat:
  enabled: true               # Toggle untuk mengaktifkan/menonaktifkan sistem combat tag
  duration: 10                # Durasi combat tag dalam detik
  prevent-commands: true      # Mencegah penggunaan command saat dalam combat
  prevent-teleport: true      # Mencegah teleportasi saat dalam combat
  punish-combat-log: true     # Bunuh pemain yang keluar saat dalam combat
  save-inventory-on-combat-log: false  # Simpan inventory pemain saat combat log (mencegah item loss)
  command-whitelist:          # Command yang tetap bisa digunakan saat dalam combat
    - "msg"
    - "r"
    - "tell"
  combat-entry-message: "&c⚔ Anda dalam combat! &7Tunggu {time} detik."
  combat-expire-message: "&a✓ Anda sudah tidak dalam combat."
  combat-log-message: "&c{player} &fkeluar saat dalam combat dan telah dibunuh!"

# Pengaturan AFK
afk:
  auto-afk:
    enabled: true      # Aktifkan deteksi AFK otomatis
    time: 300          # Waktu idle dalam detik (5 menit)
  prefix: "&7[AFK] "   # Prefix pada nama player
  tab-list-prefix: true # Tampilkan prefix AFK di tab list
  immunity-to-attacks: false # Saat AFK apakah kebal dari serangan
  visual-effects:
    enabled: true      # Aktifkan efek visual
    glowing: false     # Efek glow pada player AFK

# Pengaturan bantuan
help:
  enabled: true  # Enable custom help system
  intercept-commands: true  # Intercept and redirect commands like /plugins
  intercepted-commands:  # Additional commands to intercept
    - "/bukkit:help"
    - "/minecraft:help"
    - "/plugins"
    - "/pl"
    - "/ver"
    - "/version"